apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: concourse
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    chart: concourse
    repoURL: https://concourse-charts.storage.googleapis.com/
    targetRevision: 18.2.0
    helm:
      valuesObject:
        concourse:
          web:
            externalUrl: http://127.0.0.1:8080
            securityContext:
              privileged: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: concourse
