apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: {}
  source:
    path: manifests/image-updater
    repoURL: https://github.com/norbertkeri/bookstore.git

