apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore
  labels:
    app: bookstore
spec:
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
      - name: bookstore
        image: visko/cutters:latest
        command: ["/bookstore/target/debug/bookstore"]
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: postgres://bookstore:bookstore@db:5432/bookstore
